# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
# permalink:        pretty
# relative_permalinks: true

plugins:          [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jemoji]

# Setup
title:            Intelligent Learning Algorithms Group
tagline:          "ILAG Website"
description:      "Intelligent Learning Algorithms Group Website"
url:              https://ilag-cs.github.io/
baseurl:          /

paginate:         3

email: lucas.lehnert@usask.ca
