# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
# permalink:        pretty
# relative_permalinks: true

plugins:          [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jemoji]

# Setup
title:            Laboratory of Intelligent Learning Agents and Algorithms
tagline:          "LILAA Website"
description:      "Laboratory of Intelligent Learning Agents and Algorithms Website"
url:              https://lilaa-rl.github.io/
baseurl:          /

paginate:         3

email: lucas.lehnert@usask.ca
